<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:atlas="https://atlas.x/v1">
    <xs:element name="MT103">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="field_20" type="xs:string">
                    <xs:annotation><xs:appinfo>
                        <atlas:business-key>TransactionReference</atlas:business-key>
                    </xs:appinfo></xs:annotation>
                </xs:element>
                <xs:element name="field_50K" type="xs:string">
                    <xs:annotation><xs:appinfo>
                        <atlas:business-key>DebtorIBAN</atlas:business-key>
                    </xs:appinfo></xs:annotation>
                </xs:element>
                <xs:element name="field_59" type="xs:string">
                    <xs:annotation><xs:appinfo>
                        <atlas:business-key>CreditorIBAN</atlas:business-key>
                    </xs:appinfo></xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
